name: example
description: Example of application using the touch bar plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  touch_bar: ^0.1.0-alpha.1
  cupertino_icons: ^1.0.2

dependency_overrides:
  touch_bar_platform_interface:
    path: ../touch_bar_platform_interface
  touch_bar_macos:
    path: ../touch_bar_macos

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/plus.png
    - assets/icons/minus.png
    - assets/icons/menu.png
    - assets/icons/menu-2.png
