name: touch_bar_macos
description: macOS implementation of the touch_bar plugin.
version: 0.0.1-alpha.2
homepage: https://github.com/vital-edu/touch_bar_flutter_plugin/tree/master/touch_bar_macos
repository: https://github.com/vital-edu/touch_bar_flutter_plugin/

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: TouchBarPlugin
        fileName: touch_bar_macos.dart

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.8 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.9.0
