name: touch_bar
description: A Flutter plugin to interact with the touch bar of supported models of MacBook Pro, providing dynamic contextual controls.
version: 0.1.0-alpha.1
homepage: https://github.com/vital-edu/touch_bar_flutter_plugin/tree/master/touch_bar
repository: https://github.com/vital-edu/touch_bar_flutter_plugin/

flutter:
  plugin:
    platforms:
      macos:
        default_package: touch_bar_macos

dependencies:
  flutter:
    sdk: flutter
  touch_bar_platform_interface: ^0.1.0-alpha.1
  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
  # TODO(vital_edu): Revisit this (either update this part in the  design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264
  touch_bar_macos: ^0.1.0-alpha.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
  pedantic: ^1.11.1

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: '>=1.20.0'
